enum ActionTypes {
  GET_POSITIONS_REQUEST = "GET_POSITIONS_REQUEST",
  GET_POSITIONS_SUCCESS = "GET_POSITIONS_SUCCESS",
  GET_POSITIONS_FAILURE = "GET_POSITIONS_FAILURE",

  GET_POSITION_REQUEST = "GET_POSITION_REQUEST",
  GET_POSITION_SUCCESS = "GET_POSITION_SUCCESS",
  GET_POSITION_FAILURE = "GET_POSITION_FAILURE",
}

export default ActionTypes